### ISSUE TITLE
能不能增加向上翻页，向下翻页的快捷键。就用“<”“>”按键。

### ISSUE THREAD

**Issue by kethoven** [ywzhaiqi/userscript#102]
能不能增加向上翻页，向下翻页的快捷键。就用“<”“>”按键。
因为有时候多翻页了，想要上一页就有些麻烦，就希望在原本手部的位置——“空格键”附近，直接向上翻页。“<”“>”这两个按键就非常合适。手的位置都不用移动，一个手指简单移动就可以实现。
pgup pgdn位置太高，太麻烦了。

**Comment by yfdyh000** [comment]
你先说一下是哪个脚本……

**Comment by kethoven** [comment]
小说阅读脚本。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "YFdyh000"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 晚上8:34
收件人: "ywzhaiqi/userscript"<userscript@noreply.github.com&gt;; 
抄送: "kethoven"<1021088760@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ywzhaiqi/userscript] 能不能增加向上翻页，向下翻页的快捷键。就用“<”“&gt;”按键。 (#102)





 
你先说一下是哪个脚本……

**Comment by kethoven** [comment]
小说阅读脚本

**Comment by kethoven** [comment]
> 
> 
> 你先说一下是哪个脚本……
小说阅读脚本。
一直没找到除了PGUP以外的向上翻页快捷键。我自己的习惯是用空格键，向下翻页，但是有时候翻多了，就比较麻烦。
就希望能够直接不移动手的位置，直接向上翻页。

**Comment by kethoven** [comment]
> 
> 
> 你先说一下是哪个脚本……

小说阅读脚本。
一直没找到除了PGUP以外的向上翻页快捷键。我自己的习惯是用空格键，向下翻页，但是有时候翻多了，就比较麻烦。
就希望能够直接不移动手的位置，直接向上翻页。

**Comment by yfdyh000** [comment]
https://greasyfork.org/zh-CN/scripts/292-my-novel-reader
【Left 键滚到上一页，到顶部则打开上一章
Right 键滚到下一页，到底部则打开下一章】
不行吗？

**Comment by kethoven** [comment]
> 
> 
> https://greasyfork.org/zh-CN/scripts/292-my-novel-reader
> 【Left 键滚到上一页，到顶部则打开上一章
> Right 键滚到下一页，到底部则打开下一章】
> 不行吗？

试过很多遍，都是只可以上一章，下一章。完全不可以上一页，下一页。

**Comment by yfdyh000** [comment]
> > https://greasyfork.org/zh-CN/scripts/292-my-novel-reader
> > 【Left 键滚到上一页，到顶部则打开上一章
> > Right 键滚到下一页，到底部则打开下一章】
> > 不行吗？
> 
> 试过很多遍，都是只可以上一章，下一章。完全不可以上一页，下一页。

我试了可以。好像是设计原因，返回已读章节是直接章节跳转，未读章节按方向键右则智能翻页。
翻页也有问题，以 http://www.shouda8.com/11342/1337669.html 为例（需要加到脚本'包含'），未读章节向右，只展示了章节开头和末尾。
或许是bug。

**Comment by kethoven** [comment]
> 
> 
> > > https://greasyfork.org/zh-CN/scripts/292-my-novel-reader
> > > 【Left 键滚到上一页，到顶部则打开上一章
> > > Right 键滚到下一页，到底部则打开下一章】
> > > 不行吗？
> > 
> > 
> > 试过很多遍，都是只可以上一章，下一章。完全不可以上一页，下一页。
> 
> 我试了可以。好像是设计原因，返回已读章节是直接章节跳转，未读章节按方向键右则智能翻页。
> 翻页也有问题，以 http://www.shouda8.com/11342/1337669.html 为例（需要加到脚本'包含'），未读章节向右，只展示了章节开头和末尾。
> 或许是bug。

我的是基本上就是章节跳转，向上翻页就只能pgup

**Comment by ywzhaiqi** [comment]
新版本将会加上。
