### ISSUE TITLE
几个小说干扰文字

### ISSUE THREAD

**Issue by renyouguo** [ywzhaiqi/userscript#36]
[一世之尊 - 第一百九十章 水藏大海（第三更求月票）](http://www.wcxiaoshuo.com/wcxs-41984-11921729/)
> {无＋错}小说www.ＷＣxＩaＯＳＨuo.com

[守望黎明号 - 第一百六十七章 女王（或许是番外）](http://www.shumilou.com/shouwangliminghao/2564809.html)
> 纯文字在线阅读本站域名 www.Shumilou.com 手机同步阅读请访问 M.Shumilou.com

[异界最强战斗法师 - 卷十 章三十六 医疗](http://www.wcxiaoshuo.com/wcxs-38957-11929974/)
> 咦》无>错》小说 www.ＷＣxiaＯsＨＵo.com？

**Comment by ywzhaiqi** [comment]
fixed
