### ISSUE TITLE
似乎导致https://share.dmhy.org/页面崩溃

### ISSUE THREAD

**Issue by mzhboy** [ywzhaiqi/userscript#37]
Chrome beta v40.0.2214.69
Tampermonkey stable v3.9.202
[动漫花园](https://share.dmhy.org/)加载完后页面崩溃
我现在手动修改Super_preloaderPlus_one添加了exclude解决，
在Super_preloaderPlus_one设置页面添加排除页面也能解决

不过firefox上没有问题

**Comment by ywzhaiqi** [comment]
试了下，动漫花园默认不能翻页

**Comment by mzhboy** [comment]
在另一台PC上测试，又没问题了，不知道这是咋个回事
