### ISSUE TITLE
Super_preloaderPlus 默认启用自动翻页已选, 但是遇到无高级规则网站时, "使用翻页模式"需要每次都勾选

### ISSUE THREAD

**Issue by convexshiba** [ywzhaiqi/userscript#38]
使用的是Chrome39稳定版+TamperMonkey
请问这样是正常行为么?

**Comment by yfdyh000** [comment]
好像保存时会使用当前的网址层级作为url匹配器。如果保存时在网站首页，那么该域名下所有页面都能生效。如果层级是板块，该板块下生效。如果URL不相关，则需要反复保存多份。
