### ISSUE TITLE
 picViewer CE 報錯

### ISSUE THREAD

**Issue by ldong** [ywzhaiqi/userscript#41]
Issue: NLF版本的或者CE版本都報錯,

Browser: Chrome 41 

Webpage: gist.github.com

```javascript
Refused to execute inline script because it violates the following Content
Security Policy directive: "script-src 'unsafe-eval' 'self'
https://gist-assets.github.com *.google-analytics.com
https://collector-cdn.github.com". Either the 'unsafe-inline' keyword, a hash
('sha256-...'), or a nonce ('nonce-...') is required to enable inline
execution.
```

![screen shot 2015-01-27 at 9 41 27 pm](https://cloud.githubusercontent.com/assets/5491695/5932985/4bb6ee7e-a66d-11e4-98f7-17fdcf064cfc.png)

**Comment by ywzhaiqi** [comment]
这很正常，github 禁止执行脚本。

**Comment by ldong** [comment]
哦, 這個是因為Server端的設置嗎? 如果可能, 能否在Chrome裡面設置讓這個Error去掉嘛? 謝謝. @ywzhaiqi

**Comment by ywzhaiqi** [comment]
在 Tampermonkey 中排除这个网址
