### ISSUE TITLE
Super_preloaderPlus_one 论坛翻页导致flash无法显示

### ISSUE THREAD

**Issue by renyouguo** [ywzhaiqi/userscript#42]
一道有意思的死活题，谁来试试？ - 棋友交流 - 棋友家园
http://bbs.weiqitv.com/forum.php?mod=viewthread&tid=11136

自动翻页到39楼，只剩下两行文字了，而事实上应该有个flash
http://bbs.weiqitv.com/forum.php?mod=viewthread&tid=11136&page=4#pid116384

另外，这个脚本怎么在greasyfork被删除了？

**Comment by ywzhaiqi** [comment]
很正常，改用 iframe 方式试试。**此脚本已停止更新**。
