### ISSUE TITLE
小说阅读脚本 BUG

### ISSUE THREAD

**Issue by kidzgy** [ywzhaiqi/userscript#43]
http://www.shushuw.cn/shu/28211/4346175.html
自动进入阅读模式后，就无法再退出。或者有时候，根本不会自动进入阅读模式。
或是，勾选强制手动，就进不了阅读模式。

http://www.xxsy.net/books/587229/6238787.html
无法退出阅读模式。

**Comment by ywzhaiqi** [comment]
完全正常。请勿使用破解右键之类的脚本，此类脚本会有影响。

**Comment by kidzgy** [comment]
额，还真是用了破解右键类脚本。刚刚试出来是那个脚本问题想过来反馈，你就发帖了。

不好意思了~也谢谢解答。

**Comment by kidzgy** [comment]
对了，能不能像autopagerize，可以自定义设置翻N页，这样我就能全选保存为TXT了，超级方便。

**Comment by ywzhaiqi** [comment]
没有计划。有个导出 txt 功能，会导出之后的所有章节的 txt。
