### ISSUE TITLE
greasyfork 上的 Super_preloaderPlus_one 怎么了

### ISSUE THREAD

**Issue by yfdyh000** [ywzhaiqi/userscript#45]
@ywzhaiqi 
https://greasyfork.org/scripts/293-super-preloaderplus-one
Script has been deleted.

**Comment by Firef0x** [comment]
@yfdyh000 ，您好！

很遗憾，**此脚本已停止更新**。 :sob:

见 https://github.com/ywzhaiqi/userscript/issues/42#issuecomment-73459909 。

此致！

**Comment by yfdyh000** [comment]
谢谢回复……

**Comment by Firef0x** [comment]
@yfdyh000 不客气……现在 Y 大现身也少了，我提的 Issue 一个多月了也没有回应 :sob: :cry:
