### ISSUE TITLE
69书的读取不到内容，无法加载

### ISSUE THREAD

**Issue by kingour** [ywzhaiqi/userscript#51]
http://www.69shu.com/txt/18865/11577144
配好规则后，console里显示“当前页面没有找到内容”

**Comment by kingour** [comment]
这个是不是要自己写抓取规则才行，user.js源代码？

**Comment by ywzhaiqi** [comment]
下个版本修正

**Comment by kingour** [comment]
新推送的版本已经正常了，感谢作者~
