### ISSUE TITLE
关于picviewerCE 看图全屏问题

### ISSUE THREAD

**Issue by LiteCoder** [ywzhaiqi/userscript#52]
你好，首先感谢分享修改的picviewerCE，看图非常好用。想问下 进入幻灯查看图片 能不能自动全屏，目前需要手动点击才能进入全屏模式，不太方便。尝试自己修改未果。

**Comment by ywzhaiqi** [comment]
尝试了下，好像不行。全屏的 api 只能手动点击使用。

>Failed to execute 'requestFullScreen' on 'Element': API can only be initiated by a user gesture.

**Comment by LiteCoder** [comment]
知道了 感谢回复。
