### ISSUE TITLE
请求支持欢乐书客

### ISSUE THREAD

**Issue by lgmxiii** [ywzhaiqi/userscript#66]
www.hbooker.com

**Comment by ywzhaiqi** [comment]
不是默认支持吗？示例网址：http://www.hbooker.com/chapter/book_chapter_detail/100566098
![image](https://cloud.githubusercontent.com/assets/3016136/25069785/3287197c-22be-11e7-8852-9fe45405d61f.png)

**Comment by lgmxiii** [comment]
看了一下代码。发现include虽然适配了HTTP/S, 但是siteName中的url还只是http。改为https后可以了。

**Comment by ivysrono** [comment]
@lgmxiii include 适配 https 是我之前干的 https://github.com/ywzhaiqi/userscript/pull/64 无脑替换法。
当时以为起点以外就读零零不安全支持https就没多关。
现在看来应该更无脑一点。
@ywzhaiqi 要不要把 url: "^http:// 全部替换为 url: "^https?://
