### ISSUE TITLE
UU看书的文字广告过滤该更新了(&其他)

### ISSUE THREAD

**Issue by 821938089** [ywzhaiqi/userscript#67]
示例地址:http://www.uukanshu.net/b/36292/151233.html
而且我发现广告是动态更新的，每刷新一次就变一次:
'UU看书 www.uｕkanshu.net '
'UU看书 www.uuｋanshu．net'
'ＵU看书 www.ｕuｋanｓhu.net'
'UU看书 www.uuｋanshu.net '
'ＵU看书www．uukansｈu.net '
'UU看书 www.uukanshu.net'
'ＵU看书 www.uukanshu.net'
'ＵU看书 www.ｕukanshu.net '
'UU看书 www.uukａnshu.net '
‘UU看书 www.uukanshu．net ’
‘UU看书 www.uukａnｓhu．net ’
‘UU看书 www.uｕkansｈu．net ’
(注意有些内容是有空格的)
.......不止这些，好像还有很多
变化好像只有全角和半角的区别，没发现别的了
——————————————————————————————————
有时某些章节(http://www.uukanshu.net/b/36292/151233.html )底部会有
‘()

　　请记住本书首发域名：。笔趣阁手机版阅读网址：’
这样的内容，最好也能过滤一下。
——————————————————————————————————
还有的就是这本书的作者写作习惯问题，这里可以参考一下(可以无视)
这本书里的某些起点会屏蔽的字作者会用‘1’隔开，希望可以过滤一下。
例如’牛1b’、‘微1博’、内1衣
——————————————————————————————————
www.miaobige.com ( http://www.miaobige.com/read/11180/5216676.html ) 的章节采用了防盗，导致有可能会出现某些章节显示不全。
还有一些类似模版的网站
http://www.52dsm.com/chapter/5249/4003796.html
http://www.banfusheng.com/chapter/1008011180/5544378.html

**Comment by ywzhaiqi** [comment]
你这网址我只有代理后才能正常访问，否则
![2017-07-19_120548](https://user-images.githubusercontent.com/3016136/28350327-d94d3e52-6c7a-11e7-95e2-2a743d47253e.jpg)
