### ISSUE TITLE
为什么不在GreasyFork搞脚本呢

### ISSUE THREAD

**Issue by langren1353** [ywzhaiqi/userscript#71]
感觉GreasyFork人还是挺多的，但是发现Super_preloader在GreasyFork没有地址，所以特意前来问问大神
顺便希望给个推荐位置：https://github.com/langren1353/GM_script

**Comment by ywzhaiqi** [comment]
Super_preloader 我没用了，已不在更新

**Comment by langren1353** [comment]
不是几天前才更新么P_P
不会是自动更新的吧

**Comment by ywzhaiqi** [comment]
非本人更新，是他人提交的。

**Comment by gggccc44** [comment]
GreasyFork貌似把Super_preloaderPlus_one割了，GreasyFork不允许调用第三方脚本貌似，很多脚本被割了，这么做的原因是因为当年userscripts.org没做限制出了很多垃圾钓鱼脚本

有第三方更新也不错，幸好Super_preloaderPlus_one脚本里面留了这里的地址，不然找不到，搜索引擎貌似直接搜不到这里

**Comment by ywzhaiqi** [comment]
@gggccc44  非也，是当年我没打算继续维护，就在 GreasyFork 删了 :sweat:

**Comment by langren1353** [comment]
@ywzhaiqi 要不还是弄上去吧，这脚本这么好用的~~有更新就行了

**Comment by ywzhaiqi** [comment]
@langren1353 你可以去发布，接手维护。

**Comment by langren1353** [comment]
@ywzhaiqi 我想，但是我做不到啊，看都看不懂P_P。接手有难度

**Comment by waldens** [comment]
@ywzhaiqi 那前辈目前用什么翻页工具呢？还是说，已经没有自动翻页的需求？
