### ISSUE TITLE
My Novel Reader 另存为txt的功能中，免费和收费章节

### ISSUE THREAD

**Issue by sapqianjin** [ywzhaiqi/userscript#73]
在起点中文网，使用另存为txt的功能时，如果前面的章节是免费章节，但后面的是收费章节（已经付费）。但似乎无法自动切换抓取地址。目前只能手工点击收费章节部分的第一章，然后才能抓取后续的章节。但这样的话前面的免费章节就漏掉了。

另外收费章节中如果有一章未订阅，那么后续就都无法继续执行另存为的功能。建议如果可以的话，自动跳过未订阅章节。如果不容易实现，也可以将前面的已经保存的部分生成文件，否则用户订阅该章节后还要再从头执行一遍。

谢谢。

**Comment by ywzhaiqi** [comment]
>如果前面的章节是免费章节，但后面的是收费章节（已经付费）。但似乎无法自动切换抓取地址。

起点 限时免费 是会全部下载的。你这个订阅后不会继续下载，我也搞不清什么情况。能否把你订阅后一个章节的源码发过来看看。用浏览器另存为 `仅HTML`，然后拖到这里输入框即可。

>自动跳过未订阅章节

由于目前的下载模块太简陋了，不好实现。

>如果不容易实现，也可以将前面的已经保存的部分生成文件，否则用户订阅该章节后还要再从头执行一遍。

不是判断为 vip-limit，就会生成文件下载。没懂这个意思。

**Comment by sapqianjin** [comment]
举例来说1-54章是免费章节，55-200章是收费章节，假设第160章没有订阅。附件054是最后一章免费章节，055是第一个收费章节的样例。因为不支持HTML，所以用ZIP压缩。

目前遇到的情况是如果从1章开始下载，在下载到54章时候就会停滞，不会继续下载后续的收费章节。

从55章开始可以下载，但到第160章的时候也会停下，而且不会生成文本文件。如果不能自动跳到161的话，希望这个时候也将55-159的内容保存成一个文本文件。这样用户下次订阅160章后，可以直接从160章开始下载，而不是再次从55章下载。

谢谢。
[Novel.zip](https://github.com/ywzhaiqi/userscript/files/1310122/Novel.zip)

**Comment by ywzhaiqi** [comment]
关于下载这方面 [【小说】下载脚本](https://greasyfork.org/zh-CN/scripts/21515-noveldownloader) 更好。

**Comment by sapqianjin** [comment]
谢谢 :+1:
