### ISSUE TITLE
你好，发现My Novel Reader与贴吧全能助手冲突

### ISSUE THREAD

**Issue by kohyzsc123** [ywzhaiqi/userscript#75]
你好，发现My Novel Reader与贴吧全能助手冲突，在开启贴吧全能助手脚本的时候，使用javascript:readx();无法调用My Novel Reader脚本，如果可以解决的话非常感谢。
感谢你维护这么好的脚本！

**Comment by ywzhaiqi** [comment]
查看了下，是 全能助手脚本 设置了 `Object.freeze` 函数为 null，造成 My Novel Reader 依赖的 vue 库无法顺利执行。
> //百度贴吧：不登录即可看贴 by VA
>unsafeWindow.Object.freeze = null;

如要正常使用，需对 全能助手脚本 的 7063 行进行如下修改。不过 全能助手脚本会对内容进行重组，readx 无法获取内容。。。
```js
//百度贴吧：不登录即可看贴 by VA
unsafeWindow.Object.freeze = function(){};
```

**Comment by kohyzsc123** [comment]
谢谢回复！了解了！
