### ISSUE TITLE
关于网页内存占用以及语音朗读功能的一些问题&其他的建议

### ISSUE THREAD

**Issue by 821938089** [ywzhaiqi/userscript#78]
阅读小说过多的章节会导致网页储存过多的章节占用大量内存。
其实刷新一下网页就好了，最好就做一个历史章节限制，超过一定数量的章节就删除。

语音朗读功能无法使用，点击开始朗读无反应，音高（具体说是左下角）下面有个下拉式列表框，里面无内容。
浏览器版本：Chromium 版本 64.0.3282.119（正式版本）Built on Ubuntu , running on Ubuntu 16.04 （32 位）
拓展版本：Tampermonkey 4.5
脚本版本：6.2.8

建议做一个自动小说阅读的功能，可以调节速度，快捷键开启/关闭。
PS.希望可以有几种阅读方式，参考小说阅读软件的阅读方式。

**Comment by ywzhaiqi** [comment]
不是图片章节内存占用不大吧。

语音朗读没用内置语音是 ubuntu 系统问题吧。

自动阅读功能目前没有计划。
