### ISSUE TITLE
對不起，我又來了，思兔又不能自動翻了

### ISSUE THREAD

**Issue by ivansgo** [ywzhaiqi/userscript#86]
https://www.sto.cx/book-171612-1.html
以這個網頁為例，之前設定都可以用，昨天開始突然不能翻頁了，可以請您看一下之前的設定有什麼問題嗎？
[    {siteName: "思兔閱讀",
        url: "<a href="http://www\\.sto\\.cx/\\d+-\\d+/"; target="_blank" rel="nofollow">http://book\\.sto\\.cc/\\d+-\\d+/</a>",
        titleReg: "(.*?)_(.*?)_全文在線閱讀_思兔",
        titlePos: 0,
        //bookTitleSelector: "h1",
        prevSelector: "a:contains('上壹頁')",
        nextSelector: "a:contains('下壹頁')",
        contentSelector: "div#BookContent",
        contentRemove: 'span',
    },]

**Comment by hinaru** [comment]
我是只有把 6.3.4 版本的網址改成新的，目前看起來運作正常

```
  {siteName: "思兔阅读",
      url: "^https?://\\w+\\.sto\\.(cc|cx)/book-\\d+-\\d+.html",
      titleReg: "(.*?)_(.*?)_全文在線閱讀_思兔",
      titlePos: 0,
      //bookTitleSelector: "h1",
      prevSelector: "a:contains('上壹頁'), a:contains('上壹页')",
      nextSelector: "a:contains('下壹頁'), a:contains('下壹页')",
      contentSelector: "div#BookContent",
      contentRemove: 'span',
  },
```
