### ISSUE TITLE
站点适配申请 -> 刺猬猫阅读（原欢乐书客）

### ISSUE THREAD

**Issue by NEANC** [ywzhaiqi/userscript#88]
### 刺猬猫阅读
https://www.ciweimao.com/

### 说明
某污客搞事情，玩了手站点+APP双开 emmmm

（意思就是欢乐书客可以不用删

**Comment by ywzhaiqi** [comment]
6.3.5 已加

**Comment by NEANC** [comment]
非常感谢dalao的更新。
